version: "3.8"

services:
  # Firebase Firestore
  database:
    image: goatlab/firebase-emulator:latest
    ports:
      - 8080:8080
      - 4000:4000
    volumes:
      - ./firebaseSeed:/app/firebaseSeed
    command: firebase emulators:start --project highlevel-68ed3 --only firestore --import='./firebaseSeed' --export-on-exit

  # NestJS Services
  api:
    build:
      dockerfile: Dockerfile
      context: ./services
    environment:
      PORT: 3000
      ENVIRONMENT: local
      FIRESTORE_EMULATOR_HOST: database:8080
      GOOGLE_APPLICATION_CREDENTIALS: 
    ports:
      - 3000:3000
    links:
      - database
  
  # Angular Webapp
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./webapp
    ports:
      - 4200:80
    links:
      - api